export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_TIMEOUT = 'AUTH_TIMEOUT'
export const AUTH_UPDATE_TIMEOUT = 'AUTH_UPDATE_TIMEOUT'

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'

export const UPDATE_PAGE_FIELDS = 'UPDATE_PAGE_FIELDS'